# Generated by Django 2.2.12 on 2020-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200519_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像'),
        ),
        migrations.AddField(
            model_name='store',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='店舗'),
        ),
    ]
