# Generated by Django 2.2.12 on 2020-05-20 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200520_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='person',
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
