# Generated by Django 2.2.12 on 2020-05-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200521_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='first_name',
            field=models.CharField(default='test', max_length=100, verbose_name='姓'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_name',
            field=models.CharField(default='test', max_length=100, verbose_name='名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='tel',
            field=models.CharField(default='test', max_length=100, verbose_name='電話番号'),
            preserve_default=False,
        ),
    ]
