# Generated by Django 2.2.12 on 2020-05-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200521_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
    ]
