# Generated by Django 2.2.12 on 2020-05-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_schedule_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Booking',
        ),
    ]
