# Generated by Django 2.2.12 on 2020-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200522_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号'),
        ),
    ]
