# Generated by Django 2.2.12 on 2020-05-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200522_1748'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staff',
            name='unique_staff',
        ),
    ]
